name: uber_splash_screen
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    
flutter_launcher_icons:
  image_path: 'assets/images/icon.png'
  remove_alpha_ios: true
  min_sdk_android: 21
  adaptive_icon_background: '#000000'
  adaptive_icon_foreground: 'assets/images/icon.png'
  adaptive_icon_foreground_inset: 25

  ios: true
  android: true
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter_native_splash:
  color: '#020002'
  image: 'assets/images/logo.png'

  android_12:
    image: 'assets/images/logo_android_12.png'
    color: '#020002'

  ios: true
  android: true
  web: false